package au.edu.unimelb.campuscompanion.ui.model

import au.edu.unimelb.campuscompanion.data.model.GroupInvite

/** Accept only app invitations or complete six-character codes, never arbitrary scanned URLs. */
fun groupInviteFromQr(contents: String): String? {
    val value = contents.trim()
    val token = GroupInvite.tokenFromUri(value)
    if (token != null) {
        // Invitations generated by the service use URL-safe tokens. Do not accept extra URI fields.
        return value.takeIf { token.all { it in 'a'..'z' || it in 'A'..'Z' || it in '0'..'9' || it == '-' || it == '_' } }
    }
    return GroupInvite.joinCodeFromText(value)
}
